-- RC15 #12 — MVP3 3-vs-3 team competition (WBO Masters League parity).
-- Additive only: five new models (Team, TeamMember, TeamTournamentEntry,
-- TeamTournamentSlot, TeamMatch), one enum (TeamRole), one flag on Tournament (teamMode)
-- and one nullable self-FK on Match (teamMatchId → the parent TeamMatch for team-mode
-- sub-games). No existing table/column is altered beyond the two additive columns.
-- Design: master-plan MVP3 sketch — Team is a separate aggregate from Club (competitive
-- roster of exactly 3, optionally club-affiliated via nullable clubId); the bracket unit in
-- team mode is a TeamMatch encounter (best-of-3 over three slot-vs-slot sub-matches) built
-- on top of the existing Match/Ruleset machinery, not a replacement of it.
-- SQL generated by `prisma migrate diff --from-schema-datamodel ... --script` (no local
-- Postgres available; byte-compared against the datamodel diff) — do not hand-tweak.

CREATE TYPE "TeamRole" AS ENUM ('CAPTAIN', 'MEMBER');
ALTER TABLE "Tournament" ADD COLUMN     "teamMode" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Match" ADD COLUMN     "teamMatchId" TEXT;
CREATE TABLE "Team" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "clubId" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Team_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "TeamMember" (
    "id" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "role" "TeamRole" NOT NULL DEFAULT 'MEMBER',
    "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TeamMember_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "TeamTournamentEntry" (
    "id" TEXT NOT NULL,
    "tournamentId" TEXT NOT NULL,
    "teamId" TEXT NOT NULL,
    "checkedIn" BOOLEAN NOT NULL DEFAULT false,
    "withdrawn" BOOLEAN NOT NULL DEFAULT false,
    "seed" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TeamTournamentEntry_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "TeamTournamentSlot" (
    "entryId" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "userId" TEXT NOT NULL,
    "deckId" TEXT,
    "lockedBuildIds" TEXT[] DEFAULT ARRAY[]::TEXT[],
    CONSTRAINT "TeamTournamentSlot_pkey" PRIMARY KEY ("entryId","position")
);
CREATE TABLE "TeamMatch" (
    "id" TEXT NOT NULL,
    "tournamentId" TEXT NOT NULL,
    "stageId" TEXT NOT NULL,
    "team1EntryId" TEXT,
    "team2EntryId" TEXT,
    "round" INTEGER NOT NULL DEFAULT 0,
    "bracketOrder" INTEGER NOT NULL DEFAULT 0,
    "bracketSide" "BracketSide",
    "status" "MatchStatus" NOT NULL DEFAULT 'PENDING',
    "winsTeam1" INTEGER NOT NULL DEFAULT 0,
    "winsTeam2" INTEGER NOT NULL DEFAULT 0,
    "winnerEntryId" TEXT,
    CONSTRAINT "TeamMatch_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Team_slug_key" ON "Team"("slug");
CREATE INDEX "TeamMember_userId_idx" ON "TeamMember"("userId");
CREATE UNIQUE INDEX "TeamMember_teamId_userId_key" ON "TeamMember"("teamId", "userId");
CREATE INDEX "TeamTournamentEntry_tournamentId_checkedIn_idx" ON "TeamTournamentEntry"("tournamentId", "checkedIn");
CREATE UNIQUE INDEX "TeamTournamentEntry_tournamentId_teamId_key" ON "TeamTournamentEntry"("tournamentId", "teamId");
CREATE UNIQUE INDEX "TeamTournamentSlot_entryId_userId_key" ON "TeamTournamentSlot"("entryId", "userId");
CREATE INDEX "TeamMatch_stageId_round_bracketOrder_idx" ON "TeamMatch"("stageId", "round", "bracketOrder");
CREATE INDEX "TeamMatch_tournamentId_idx" ON "TeamMatch"("tournamentId");
ALTER TABLE "Match" ADD CONSTRAINT "Match_teamMatchId_fkey" FOREIGN KEY ("teamMatchId") REFERENCES "TeamMatch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Team" ADD CONSTRAINT "Team_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Team" ADD CONSTRAINT "Team_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TeamMember" ADD CONSTRAINT "TeamMember_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamMember" ADD CONSTRAINT "TeamMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamTournamentEntry" ADD CONSTRAINT "TeamTournamentEntry_tournamentId_fkey" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamTournamentEntry" ADD CONSTRAINT "TeamTournamentEntry_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamTournamentSlot" ADD CONSTRAINT "TeamTournamentSlot_entryId_fkey" FOREIGN KEY ("entryId") REFERENCES "TeamTournamentEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamTournamentSlot" ADD CONSTRAINT "TeamTournamentSlot_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamTournamentSlot" ADD CONSTRAINT "TeamTournamentSlot_deckId_fkey" FOREIGN KEY ("deckId") REFERENCES "Deck"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TeamMatch" ADD CONSTRAINT "TeamMatch_tournamentId_fkey" FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamMatch" ADD CONSTRAINT "TeamMatch_stageId_fkey" FOREIGN KEY ("stageId") REFERENCES "TournamentStage"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamMatch" ADD CONSTRAINT "TeamMatch_team1EntryId_fkey" FOREIGN KEY ("team1EntryId") REFERENCES "TeamTournamentEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TeamMatch" ADD CONSTRAINT "TeamMatch_team2EntryId_fkey" FOREIGN KEY ("team2EntryId") REFERENCES "TeamTournamentEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
