// lib/doubleElimination.ts
// Phase 5 Part C2 — double-elimination bracket generation + propagation mapping.
//
// Pure functions only (no DB) so the topology is unit-testable without infrastructure.
// Seeding and bye policy are reused VERBATIM from lib/bracket.ts (ascending userId; the first
// `slots − n` participants get byes as auto-completed round-1 matches) — do not reinvent them here.
//
// ═══════════════════════════════════════════════════════════════════════════════════════════
// ROUND NUMBERING AND DROP-IN MAPPING (the single most error-prone part of this feature — a
// worked example follows; change this only with a topology test in hand)
// ═══════════════════════════════════════════════════════════════════════════════════════════
// Let n = participants, slots = nextPow2(n), R = log2(slots) (winners-bracket rounds).
//
//   • Winners bracket (WB): rounds 1..R, generated by generateSingleEliminationBracket.
//   • Losers bracket (LB): rounds R+1 .. 3R−2, i.e. 2R−2 rounds. LB "sub-round" j (1-based,
//     overall round R+j) has slots / 2^(ceil(j/2)+1) matches:
//       – j odd  → a DROP-IN round: it also receives losers from a WB round.
//       – j even → a pure consolidation round (only LB winners feed it).
//   • Grand final: round 3R−1, bracketOrder 0; grand-final RESET: same round, bracketOrder 1
//     (played ONLY if the LB champion wins the first grand final — the WB champion must be
//     beaten twice. It is generated as a PENDING node; the score route DELETES it if the WB
//     champion wins the grand final — this is the one generated bracket node that may never
//     be played, and both the generate and complete routes must tolerate its absence).
//
// WB round-r losers drop into the LB per: r = 1 → LB sub-round 1; r ≥ 2 → LB sub-round 2(r−1).
//   • r = 1: WB match (1, i) loser → LB sub-round 1 match floor(i/2), slot i%2 (player1 for even i).
//     (Adjacent WB matches have disjoint players, so no rematch is possible here.)
//   • 2 ≤ r < R: WB match (r, i) loser → LB sub-round 2(r−1) match i, slot player2 (player1 is
//     the LB continuation from the previous LB round).
//   • r = R (WB final) loser → last LB round (3R−2), match 0, slot player2.
//
// LB match winner propagation: LB (R+j, i) winner →
//   • j = 2R−2 (last LB round) → grand final (3R−1, 0) slot player2 (LB champion).
//   • matches(j+1) == matches(j) (odd j → even j+1, a drop-in round) → (R+j+1, i) slot player1.
//   • otherwise (even j → odd j+1, consolidation, round size halves) → (R+j+1, floor(i/2)),
//     slot by parity — identical to the single-elimination rule.
//
// WORKED EXAMPLE — 8 participants p1..p8 (ascending userId), slots=8, R=3:
//   WB  R1: (1,0) p1vsp2 · (1,1) p3vsp4 · (1,2) p5vsp6 · (1,3) p7vsp8
//       R2: (2,0) · (2,1) empty            R3: (3,0) WB final, empty
//   LB  R4 (j=1, drop-in from WB R1): (4,0) ← losers of WB (1,0)+(1,1); (4,1) ← losers of (1,2)+(1,3)
//       R5 (j=2, drop-in from WB R2): (5,0) ← winner(4,0) vs loser(2,0); (5,1) ← winner(4,1) vs loser(2,1)
//       R6 (j=3, consolidation):      (6,0) ← winner(5,0) vs winner(5,1)
//       R7 (j=4, WB-final drop-in):   (7,0) ← winner(6,0) vs loser(3,0)
//   GF  R8: (8,0) WB champion vs LB champion · (8,1) RESET, played only if (8,0) is won by the
//       LB champion (player2); otherwise the score route deletes (8,1).
//   Elimination: the loser of ANY LB match is eliminated (StageStanding.eliminated = true). The
//   loser of a WB match is NOT eliminated — they drop into the LB. The loser of grand final (8,0)
//   is NOT eliminated (they get the reset); the loser of the reset IS eliminated.
//
// BYES IN DOUBLE-ELIMINATION (documented decision): WB byes produce no loser, so the LB slots
// they would have fed can never fill. Two structural consequences, both handled at runtime by
// the "stuck-bye" rule in lib/stageFlow.ts (never at generation time, except the dead-match
// case below):
//   • An LB round-1 match whose TWO feeder WB matches are both byes is generated immediately as
//     COMPLETED with winnerId = null (a structural no-op shell) — otherwise the stage could
//     never complete. Its downstream LB slot stays empty until the sibling feeder (a real WB
//     loser) arrives, at which point the stuck-bye rule resolves that match as a bye.
//   • Any other LB match that ends up with exactly one live player whose sibling feeder is a
//     completed bye/shell auto-completes as a bye for the live player (winnerId = that player,
//     status COMPLETED, same representation as a single-elimination bye) and its win propagates.
import type { BracketNode } from '@/lib/bracket'
import { generateSingleEliminationBracket } from '@/lib/bracket'
import type { TournamentParticipant } from '@prisma/client'

export type DoubleEliminationBracket = {
  winners: BracketNode[]
  losers: BracketNode[]
  grandFinal: BracketNode
  grandFinalReset: BracketNode
}

export type SlotTarget = { round: number; bracketOrder: number; slot: 'player1Id' | 'player2Id' }

export type WinnerPropagation =
  | { type: 'slot'; target: SlotTarget }
  | { type: 'grand-final'; slot: 'player1Id' | 'player2Id' } // WB champion → GF player1, LB champion → GF player2
  | { type: 'none' } // grand final / reset: no slot to advance into

export type LoserPropagation =
  | { type: 'slot'; target: SlotTarget }
  | { type: 'not-eliminated' } // WB loser drops into the LB; grand-final loser gets the reset
  | { type: 'eliminated' } // LB match loser (and reset loser) is out after their 2nd loss

function nextPow2(n: number): number {
  let slots = 1
  while (slots < n) slots *= 2
  return slots
}

/** Winners-bracket round count R for a participant count (log2 of the next power of 2). */
export function winnersRounds(participantCount: number): number {
  return Math.log2(nextPow2(participantCount))
}

/** Matches in LB sub-round j (1-based), given slots = nextPow2(n). */
function lbMatches(slots: number, j: number): number {
  return slots / 2 ** (Math.ceil(j / 2) + 1)
}

/**
 * Generate the full double-elimination bracket. Requires ≥ 3 participants (with 2 players a
 * double-elimination is degenerate — the generate route must refuse earlier); returns null below
 * that. The winners array is exactly generateSingleEliminationBracket's output (byes included).
 */
export function generateDoubleEliminationBracket(
  participants: Pick<TournamentParticipant, 'userId'>[]
): DoubleEliminationBracket | null {
  const sorted = [...participants].sort((a, b) => (a.userId < b.userId ? -1 : a.userId > b.userId ? 1 : 0))
  const count = sorted.length
  if (count < 3) return null

  const slots = nextPow2(count)
  const R = Math.log2(slots)
  const byes = slots - count

  const winners = generateSingleEliminationBracket(participants)
  const losers: BracketNode[] = []
  for (let j = 1; j <= 2 * R - 2; j++) {
    for (let i = 0; i < lbMatches(slots, j); i++) {
      const dead = j === 1 && 2 * i + 1 < byes
      losers.push({
        round: R + j,
        bracketOrder: i,
        player1Id: null,
        player2Id: null,
        winnerId: null,
        // Both feeder WB matches are byes (no losers can ever arrive): structural no-op shell,
        // COMPLETED at generation so the stage can complete (see header comment).
        status: dead ? 'COMPLETED' : 'PENDING',
      })
    }
  }

  const grandFinal: BracketNode = {
    round: 3 * R - 1,
    bracketOrder: 0,
    player1Id: null,
    player2Id: null,
    winnerId: null,
    status: 'PENDING',
  }
  const grandFinalReset: BracketNode = {
    round: 3 * R - 1,
    bracketOrder: 1,
    player1Id: null,
    player2Id: null,
    winnerId: null,
    status: 'PENDING',
  }
  return { winners, losers, grandFinal, grandFinalReset }
}

/**
 * Where the WINNER of an elimination match advances, for a stage with the given participant
 * count. Deterministic and side-effect free — the score route persists the returned slot.
 */
export function winnerPropagation(match: { round: number; bracketOrder: number }, participantCount: number): WinnerPropagation {
  const R = winnersRounds(participantCount)
  const { round, bracketOrder: i } = match

  if (round === 3 * R - 1) return { type: 'none' } // grand final / reset
  if (round <= R) {
    // Winners bracket (single-elimination rule); the WB final winner is the GF player1.
    if (round === R) return { type: 'grand-final', slot: 'player1Id' }
    return { type: 'slot', target: { round: round + 1, bracketOrder: Math.floor(i / 2), slot: i % 2 === 0 ? 'player1Id' : 'player2Id' } }
  }
  // Losers bracket: sub-round j = round − R.
  const j = round - R
  if (j === 2 * R - 2) return { type: 'grand-final', slot: 'player2Id' } // LB champion
  const slots = 2 ** R
  if (lbMatches(slots, j + 1) === lbMatches(slots, j)) {
    return { type: 'slot', target: { round: round + 1, bracketOrder: i, slot: 'player1Id' } }
  }
  return { type: 'slot', target: { round: round + 1, bracketOrder: Math.floor(i / 2), slot: i % 2 === 0 ? 'player1Id' : 'player2Id' } }
}

/**
 * What the LOSER of an elimination match means, for a stage with the given participant count:
 * drop into the LB slot, stay alive (not eliminated), or be eliminated after a 2nd loss.
 */
export function loserPropagation(match: { round: number; bracketOrder: number }, participantCount: number): LoserPropagation {
  const R = winnersRounds(participantCount)
  const { round, bracketOrder: i } = match

  if (round === 3 * R - 1) {
    // Grand final (order 0): the WB champion gets the reset — NOT eliminated. Reset (order 1):
    // the loser is out.
    return i === 0 ? { type: 'not-eliminated' } : { type: 'eliminated' }
  }
  if (round <= R) {
    // Winners-bracket loser: drops into the LB (not eliminated) — structurally DIFFERENT from
    // winner propagation, which stays inside the same bracket side.
    if (round === 1) {
      return { type: 'slot', target: { round: R + 1, bracketOrder: Math.floor(i / 2), slot: i % 2 === 0 ? 'player1Id' : 'player2Id' } }
    }
    if (round === R) {
      return { type: 'slot', target: { round: 3 * R - 2, bracketOrder: 0, slot: 'player2Id' } }
    }
    return { type: 'slot', target: { round: R + 2 * (round - 1), bracketOrder: i, slot: 'player2Id' } }
  }
  // Losers-bracket loser: eliminated, no propagation.
  return { type: 'eliminated' }
}
